theme: minima

author: Luca Fornasari
email: fornaeffe@gmail.com

github_username:  fornaeffe
facebook_username: fornaeffe
instagram_username: fornaeffe

show_excerpts: true
excerpt_separator: <!--more-->
